name: Build-Master-Cobra
on: [push]
jobs:
  ps3-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build PKG
        run: |
          # Usamos un contenedor que ya tiene todo instalado para compilar
          docker run --rm -v $(pwd):/src psl1ght/psl1ght:latest /bin/bash -c "cd /src && make"

      - name: Upload PKG
        uses: actions/upload-artifact@v4
        with:
          name: Mi-App-PS3
          path: "./*.pkg"


