name: Build-Master-Cobra
on: [push]
jobs:
  ps3-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile with Docker Direct
        run: |
          # Este comando descarga la imagen y compila en un solo paso
          docker run --rm -v $(pwd):/src ghcr.io/mald0n/psl1ght:master /bin/bash -c "cd /src && make"

      - name: Upload PKG
        uses: actions/upload-artifact@v4
        with:
          name: MasterCobra_v7_PKG
          path: "*.pkg"


